info:
  version: 0.0.1
  title: Geddis API
  description: description
  contact:
    name: Alex Malov
    email: scukonick@gmail.com

host: 127.0.0.1:8080
swagger: "2.0"
schemes:
  ['http']
tags:
- name: "strings"
  description: "Operations with string values"

paths:
  /strings/{key}:
    get:
      tags: ["strings"]
      summary: "Get string value by key"
      description: "Returns a string value defined by specified key"
      operationId: "getStringByKey"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "key"
        in: "path"
        description: "key of value to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/StringValue"
        400:
          description: "Invalid type defined by this key"
        404:
          description: "String by this key is not found"
    post:
      tags: ["strings"]
      summary: "Set string value defined by key"
      description: "Sets string value defined by key. If TTL is omitted, \
      ttl of this value would not be set"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/SetStringValueReq"
      parameters:
      - name: "key"
        in: "path"
        description: "key of value to set"
        required: true
        type: "string"
      - name: "body"
        in: "body"
        description: "Value and ttl of the string element"
        required: true
        schema:
          $ref: "#/definitions/SetStringValueReq"
definitions:
  StringValue:
    type: string
  SetStringValueReq:
    type: object
    properties:
      value:
        type: "string"
      ttl:
        type: integer
        format: "int64"
        description: "TTL of element in seconds. If <= 0 it would be stored forever"
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    